name: Automatic deployment
on:
  push:
    branches:
      - dev
      - stg
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: check
        run: |
          echo ${{ github.ref }}" is merged!"
