name: Auto Merge and Deploy to stg - scheduled

on:
  schedule:
    - cron: "0 * * * *"
env:
  BRANCH_FROM: dev
  BRANCH_TO: stg

jobs:

  call-pr-and-merge:
    uses: a2-ito/actions-test/.github/workflows/merge-workflow.yml@dev
    with:
      branch_from: dev
      branch_to: stg
  call-deployment:
    needs: call-pr-and-merge
    uses: a2-ito/actions-test/.github/workflows/deploy-workflow.yml@dev
    with:
      branch: stg
