name: Auto merge stg2main

on:
  schedule:
    - cron: "*/30 * * * *"
env:
  BRANCH_FROM: stg
  BRANCH_TO: dev

jobs:

  call-pr-and-merge:
    uses: a2-ito/actions-test/.github/workflows/auto-merge-workflow.yml@dev
    with:
      branch_from: ${{ env.BRANCH_FROM }}
      branch_to: ${{ env.BRANCH_TO }}
  call-deployment:
    uses: a2-ito/actions-test/.github/workflows/deploy-workflow.yml@dev
    with:
      branch: ${ env.BRANCH_TO }}
