name: Automatic deployment
on:
  pull_request:
    branches:
      - dev
      - stg
      - main
    types: [closed]

jobs:
  call-deployment:
    needs: call-pr-and-merge
    uses: a2-ito/actions-test/.github/workflows/deploy-workflow.yml@dev
    with:
      branch: ${{ githu.base_ref }}
