name: Auto merge stg2main

on:
  schedule:
    - cron: "*/10 * * * *"
env:
  BRANCH_FROM: stg
  BRANCH_TO: main

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_FROM }}
      - name: Create Pull Request dev2stage
        id: create-pull-request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PULL_REQUEST_URI=$(gh pr create -B ${{ env.BRANCH_TO }} -t "Auto merge: ${{ env.BRANCH_FROM }} to ${{ env.BRANCH_TO }}" -b "")
          echo "::set-output name=PULL_REQUEST_URI::$PULL_REQUEST_URI"
      - name: Merge Pull Request dev2stage
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{steps.create-pull-request.outputs.PULL_REQUEST_URI}} --merge
