name: boolean

on:
  push:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ true || false }}
        echo ${{ false || true }}
        echo ${{ 'true' || true }}
        echo ${{ 'true' || false }}
        echo ${{ 'false' || true }}
        echo ${{ 'false' || false }}
        echo ${{ 'hoge' || true }}
        echo ${{ 'hoge' || false }}
        echo ${{ fromJson('true') || false }}
        echo ${{ fromJson('false') || true }}
