name: context
 
on:
  push:
  pull_request:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Control a condition of BG Deployment
      run: |
        echo "github.ref: ${{ github.ref }}"
        echo "github.event.label.name: ${{ github.event.label.name }}"
        echo "github.event.ref: ${{ github.event.ref }}"
        echo "github.event: ${{ github.event }}"
        echo "github.event.pull_request.base.ref: ${{ github.event.pull_request.base.ref }}"
        echo "github.event.pull_request.base_ref: ${{ github.event.pull_request.base_ref }}"
 
