name: Deployment workflow

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: check
        run: |
          echo "github.ref: "${{ github.ref}}
          echo "github.base_ref: "${{ github.base_ref}}
          echo ${{ inputs.branch }}" is merged!"
