name: Deployment workflow

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to be checked out (option)"
        required: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # todo: switch a deploy env value by inputs.branch
      - name: check
        run: |
          echo "github.ref: "${{ github.ref}}
          echo "github.base_ref: "${{ github.base_ref}}
          echo ${{ inputs.branch }}" is merged!"
