name: Manual deployment
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to be checked out (option)"
        required: false

jobs:
  call-deployment:
    needs: call-pr-and-merge
    uses: a2-ito/actions-test/.github/workflows/deploy-workflow.yml@dev
    with:
      branch: ${{ github.ref }}
